DROP TABLE IF EXISTS e_commerce ;
CREATE TABLE e_commerce  
(
	order_id VARCHAR(15) ,
	order_date  DATE, 
	product_category  VARCHAR(100),
	sales_amount FLOAT,
	quantity  INT,
	customer_id VARCHAR(15)
);

ALTER TABLE e_commerce
ADD CONSTRAINT pk_order_id
PRIMARY KEY(order_id);


--  BUSINESS GOAL:
-- "Identify which product categories are driving the most revenue, understand customer purchase behavior, 
-- and forecast sales trends."

SELECT * FROM e_commerce 
LIMIT 5;


-- checking for duplicates order_id

SELECT 
	order_id,
	count(order_id) as num_order_id
FROM e_commerce
GROUP BY 1
HAVING count(order_id) > 1;

-- result: No duplicate order_id found.

-- cheecking duplicates row

with duplicates as(
	SELECT *,
		ROW_NUMBER() OVER (PARTITION BY order_id,order_date,product_category,sales_amount,quantity,customer_id
							) AS row_number
	FROM e_commerce
)
SELECT * FROM duplicates
WHERE row_number >1;

-- result: No duplicate rows found

-- observation : data is available in standard format no standarization of data needed.
--               Also, not found any null value,no issue in date formate as well . we can start data expolration.

-- Data Exploration 

-- lets explore 'product_category' column.

SELECT product_category,
	ROUND(SUM(CAST(sales_amount AS NUMERIC)),2) AS sum_sales,
	SUM(quantity) AS Total_quantity_sold_by_product_category,
	ROUND(SUM(CAST(sales_amount AS NUMERIC)) *100.0/(SELECT SUM(CAST(sales_amount AS NUMERIC)) FROM e_commerce),2) AS percentage_revenue_share
FROM e_commerce
GROUP BY 1
ORDER BY sum_sales DESC,
	Total_quantity_sold_by_product_category  DESC ;

-- Observation :
-- 	1. Revenue generated by Electronics products are highest and total_quantity sold is 662 units
-- 	   which is ranked second with comparision with other product _category.	
-- 	2. Books generated second-most revenue by selling 643 units which is ranked third among total units sold 
--     compare to other product_category.
--  3. Clothing is most sold product selling 677 units and generated third highest revenue.
 

-- We have checked each product-wise revenue generated, quantity sold and market share.

-- Lets customer behaviour.


-- Top five customer by total_sales.

SELECT 
	customer_id,
	ROUND(SUM(CAST(sales_amount AS NUMERIC)),2) AS sum_sales,
	DENSE_RANK() OVER(ORDER BY SUM(CAST(sales_amount AS NUMERIC)) DESC) AS sales_rank
FROM e_commerce 
GROUP BY 1
ORDER BY 
	sales_rank
LIMIT 5 ;


-- Observation: 1053, 1058, 1020, 1083 and 1012 are top five customer by sales. 



-- Top five customer by total quantity purchased.

SELECT 
	customer_id,
	SUM(quantity) AS Total_quantity_purchased,
	DENSE_RANK() OVER(ORDER BY SUM(quantity) DESC) AS quantity_rank
FROM e_commerce
GROUP BY 1
ORDER BY 
	quantity_rank
LIMIT 5;


-- Observation: 1053, 1058, 1099, 1056 and 1046 are top five customer by total quantity purchased. 


WITH customer_behavior AS (
    SELECT 
        customer_id,
        EXTRACT(YEAR FROM order_date) AS year,
        EXTRACT(QUARTER FROM order_date) AS quarter,
        product_category,
        sales_amount,
        quantity
    FROM e_commerce
)
SELECT 
    customer_id,
    year,
    quarter,
    product_category,
    ROUND(SUM(CAST(sales_amount AS NUMERIC)), 2) AS sum_sales,
    SUM(quantity) AS total_quantity_purchased
FROM customer_behavior
GROUP BY 
    customer_id, year, quarter, product_category
ORDER BY 
    customer_id, year DESC, quarter DESC;


--  Customer Lifetime Value (CLV) Calculation


SELECT 
    customer_id,
    ROUND(SUM(CAST(sales_amount AS NUMERIC)), 2) AS total_sales,
    COUNT(DISTINCT order_id) AS total_orders,
    AVG(CAST(sales_amount AS NUMERIC)) AS avg_order_value
FROM e_commerce
GROUP BY customer_id
ORDER BY total_sales DESC;




--  SALES TREND

WITH order_date as
(
	SELECT 
		order_date,
		EXTRACT(YEAR FROM order_date) AS year,
		EXTRACT(QUARTER FROM order_date) AS quarter,
		sales_amount,
		quantity
	FROM e_commerce
)
SELECT 
	year,
	quarter,
	ROUND(SUM(CAST(sales_amount AS NUMERIC)),2) AS sum_sales
FROM order_date
GROUP BY 
	year,
	quarter
ORDER BY 
	year DESC,
	quarter DESC ;


WITH order_date AS (
    SELECT 
        order_date,
        EXTRACT(YEAR FROM order_date) AS year,
        EXTRACT(QUARTER FROM order_date) AS quarter,
        product_category,
        sales_amount,
        quantity,
    FROM e_commerce
)
SELECT 
    year,
    quarter,
    product_category,
    ROUND(SUM(CAST(sales_amount AS NUMERIC)), 2) AS sum_sales,
    SUM(quantity) AS total_quantity_sold
FROM order_date
GROUP BY 
    year, quarter, product_category
ORDER BY 
    year DESC, quarter DESC, sum_sales DESC;




WITH sales_growth AS (
    SELECT 
        product_category,
        EXTRACT(YEAR FROM order_date) AS year,
        ROUND(SUM(CAST(sales_amount AS NUMERIC)), 2) AS sum_sales
    FROM e_commerce
    GROUP BY product_category, year
)
SELECT 
    product_category,
    year,
    sum_sales,
    LAG(sum_sales) OVER (PARTITION BY product_category ORDER BY year) AS previous_year_sales,
    ROUND(sum_sales - LAG(sum_sales) OVER (PARTITION BY product_category ORDER BY year), 2) AS sales_growth
FROM sales_growth
ORDER BY product_category, year DESC;

-- Observation: 
-- 1. Books grew in 2024, but saw a ~24.6% decline in 2025. Indicates a shift in buyer behavior or reduced demand.
-- 2. Clothing peaked in 2024. The ~25.9% drop in 2025 is significant and may suggest overstocking, loss of interest, 
--    or rising competition.
-- 3. Electronics took the biggest hit in 2025. A nearly 46% drop after strong 2024 performance.
-- 4. All three categories show peak sales in 2024, followed by a decline in 2025. This suggests a broader business issue in 2025.


-- INSIGHTS:
-- Top Product:		Electronics generates the most revenue.
-- Top-Selling by Volume: 	Clothing sells the most units.
-- Loyal Customers:		Customers 1053 and 1058 are top-tier for retention campaigns.
-- Category Strategy:	Books are mid-range, reliable performers.
-- 2025 Risk:	All product categories saw declines; Electronics most affected.
-- Business Opportunity:	Focus retention and re-engagement strategies for 2025 to recover growth